function Signup() {

    //以下参考
    // .catch((error) => {
    //     // レスポンスありのエラーハンドリング（実際には必要に応じた例外処理を実装する）
    //     console.log(
    //       `Error! code: ${error.response.status}, message: ${error.message}`
    //     );
    //     return error.response.data;
    //   });
    return (
        <>
        </>
    );
  }
  
  export default Signup;
  